### ISSUE TITLE
Oups... phpDox encountered a problem and has terminated!

### ISSUE THREAD

**Issue by m1ket** [theseer/phpdox#103]
Hello,

I'm having an issue setting up my Jenkins installation where phpdox keeps failing. Has anyone experienced this issue before?

```
phpdox:
     [exec] 
     [exec] 
     [exec] Oups... phpDox encountered a problem and has terminated!
     [exec] It most likely means you've found a bug, so please file a report for this and paste the stacktrace (if given) along!
     [exec] 
     [exec] Exception: ErrorException
     [exec] Location: /usr/share/pear/TheSeer/phpDox/shared/Version.php (Line 61)
     [exec] 
     [exec] date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'UTC' for 'UTC/0.0/no DST' instead
     [exec] 
     [exec] #0 /usr/share/pear/TheSeer/phpDox/shared/Version.php(61): date()
     [exec] #1 /usr/share/pear/TheSeer/phpDox/CLI.php(178): TheSeer\phpDox\Version::getInfoString()
     [exec] #2 /usr/share/pear/TheSeer/phpDox/CLI.php(151): TheSeer\phpDox\CLI->showVersion()
     [exec] #3 /usr/bin/phpdox(60): TheSeer\phpDox\CLI->run()
     [exec] 
     [exec] 
     [exec] 
     [exec] Result: 1
```

**Comment by theseer** [comment]
For the record: The behavior changed for 0.8.0+ is to explicitly use PHP's fallback to UTC when the configuration is missing. I'm still not happy with that but it's at least consistent with PHPs behavior.
