### ISSUE TITLE
Pdepend exceptions resulting in D.xml not being found

### ISSUE THREAD

**Issue by greenwellness** [theseer/phpdox#140]
Here you find the exception which was printed, since it requested for a bugreport to be filed: here goes.

```
[01.04.2014 - 15:32:07] The following file(s) had errors during processing and were excluded:
[01.04.2014 - 15:32:07]  - ./lib/Mage/Connect/Package/Extension.php (finfo::file(): Failed identify data 0:(null))
[01.04.2014 - 15:32:07]  - ./downloader/lib/Mage/Connect/Package/Maintainer.php (finfo::file(): Failed identify data 0:(null))
[01.04.2014 - 15:32:07]  - ./downloader/lib/Mage/Connect/Package/Extension.php (finfo::file(): Failed identify data 0:(null))
[01.04.2014 - 15:32:07]  - ./downloader/lib/Mage/Connect/Repository/Channel/Abstract.php (finfo::file(): Failed identify data 0:(null))
[01.04.2014 - 15:32:07]  - ./downloader/lib/Mage/Connect/Repository/Channel/Core.php (finfo::file(): Failed identify data 0:(null))
[01.04.2014 - 15:32:07]  - ./downloader/lib/Mage/Connect/Repository/Channel/Commercial.php (finfo::file(): Failed identify data 0:(null))
[01.04.2014 - 15:32:07]  - ./downloader/lib/Mage/Connect/Repository/Channel/Community.php (finfo::file(): Failed identify data 0:(null))
[01.04.2014 - 15:32:07]  - ./downloader/lib/Mage/Connect/Repository/Abstract.php (finfo::file(): Failed identify data 0:(null))
[01.04.2014 - 15:32:07]  - ./downloader/lib/Mage/Connect/Repository/Channel.php (finfo::file(): Failed identify data 0:(null))
[01.04.2014 - 15:32:07]  - ./downloader/lib/Mage/Connect/Repository/Local.php (finfo::file(): Failed identify data 0:(null))
[01.04.2014 - 15:32:07]  - ./downloader/lib/Mage/Connect/Repository.php (finfo::file(): Failed identify data 0:(null))
[01.04.2014 - 15:32:07]  - ./js/fontis/tiny_mce/plugins/ibrowser/langs/sk.php (Encoding error - conversion to UTF-8 failed)
[01.04.2014 - 15:32:07]  - ./vendor/phpdocumentor/phpdocumentor/tests/data/TokenIteratorTestFixture.php (Trying to get property of non-object)
[01.04.2014 - 15:32:07]  - ./vendor/doctrine/annotations/tests/Doctrine/Tests/Common/Annotations/Fixtures/GlobalNamespacesPerFileWithClassAsFirst.php (Trying to get property of non-object)
[01.04.2014 - 15:32:07]  - ./vendor/doctrine/annotations/tests/Doctrine/Tests/Common/Annotations/Fixtures/DifferentNamespacesPerFileWithClassAsFirst.php (Trying to get property of non-object)
[01.04.2014 - 15:32:07]  - ./vendor/doctrine/annotations/tests/Doctrine/Tests/Common/Annotations/Fixtures/GlobalNamespacesPerFileWithClassAsLast.php (Trying to get property of non-object)
[01.04.2014 - 15:32:07]  - ./vendor/doctrine/annotations/tests/Doctrine/Tests/Common/Annotations/Fixtures/DifferentNamespacesPerFileWithClassAsLast.php (Trying to get property of non-object)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/bugs/076-021-tokenizer-keyword-substitution.php (Syntax error, unexpected T_NS_C on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/bugs/070/testParserThrowsExceptionForInvalidBoundClosureVariableBug70.php (Syntax error, unexpected T_STRING, expecting T_VARIABLE on line 3)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/bugs/076-020-tokenizer-keyword-substitution.php (Syntax error, unexpected T_DIR on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/bugs/076-019-tokenizer-keyword-substitution.php (Syntax error, unexpected T_NAMESPACE on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/bugs/076-023-tokenizer-keyword-substitution.php (Syntax error, unexpected T_USE, expecting T_STRING on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/bugs/076-030-tokenizer-keyword-substitution.php (Syntax error, unexpected T_DIR, expecting T_STRING on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/bugs/076-017-tokenizer-keyword-substitution.php (Syntax error, unexpected T_USE on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/bugs/116/testParserNotThrowsAnExceptionForKeywordGoto.php (Syntax error, unexpected T_GOTO, expecting T_STRING on line 4)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/bugs/116/testParserNotThrowsAnExceptionForKeywordNamespace.php (Syntax error, unexpected T_NAMESPACE, expecting T_STRING or '(' on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/bugs/116/testParserNotThrowsAnExceptionForKeywordUse.php (Syntax error, unexpected T_USE, expecting T_STRING on line 4)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/bugs/116/testParserNotThrowsAnExceptionForMagicNamespaceConstant.php (Syntax error, unexpected T_NS_C, expecting T_STRING or '(' on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/bugs/073/testParserCreatesExpectedObjectGraphClassDeclaredBeforeInterfaceWithNamespace.php (Trying to get property of non-object)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/bugs/073/testParserCreatesExpectedObjectGraphInterfaceDeclaredBeforeClassWithNamespace.php (Trying to get property of non-object)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/bugs/17264279/testParserAcceptsNamespaceAsClassName.php (Syntax error, unexpected T_NAMESPACE, expecting T_STRING on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/bugs/17264279/testParserAcceptsUseAsClassName.php (Syntax error, unexpected T_USE, expecting T_STRING on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/bugs/17264279/testParserAcceptsCloneAsClassName.php (Syntax error, unexpected T_CLONE, expecting T_STRING on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/bugs/152/testClassDeclarationAndParameterTypeHintAreReferencesToTheSameClass.php (Trying to get property of non-object)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/bugs/076-018-tokenizer-keyword-substitution.php (Syntax error, unexpected T_GOTO on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/bugs/182/testParserAcceptsCloneAsFunctionName.php (Syntax error, unexpected T_CLONE, expecting T_STRING or '(' on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/bugs/182/testParserAcceptsCloneAsInterfaceName.php (Syntax error, unexpected T_CLONE, expecting T_STRING on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/bugs/182/testParserAcceptsCloneAsClassName.php (Syntax error, unexpected T_CLONE, expecting T_STRING on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/bugs/182/testParserAcceptsCloneAsMethodName.php (Syntax error, unexpected T_CLONE, expecting T_STRING on line 4)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/bugs/065/testClassDeclarationWithExtendsWithoutClassName.php (Syntax error, unexpected EOF, expecting T_STRING or T_NAMESPACE or T_NS_SEPARATOR on line 3)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/bugs/065/testClassDeclarationWithIncompleteParentInterfaceWithoutBody.php (Syntax error, unexpected EOF, expecting T_STRING or T_NAMESPACE or T_NS_SEPARATOR on line 3)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/bugs/065/testClassDeclarationWithoutBody.php (Syntax error, unexpected EOF, expecting '{' on line 3)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/bugs/065/testClassDeclarationWithExtendsWithoutInterfaceName.php (Syntax error, unexpected EOF, expecting T_STRING or T_NAMESPACE or T_NS_SEPARATOR on line 3)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/bugs/065/testClassDeclarationWithParentInterfaceWithoutBody.php (Syntax error, unexpected EOF, expecting '{' on line 3)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/bugs/065/testInterfaceDeclarationWithoutBody.php (Syntax error, unexpected EOF, expecting '{' on line 3)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/bugs/065/testInterfaceDeclarationWithExtendWithoutBody.php (Syntax error, unexpected EOF, expecting '{' on line 3)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/bugs/065/testInterfaceDeclarationWithInvalidInterfaceList.php (Syntax error, unexpected '{', expecting T_STRING or T_NAMESPACE or T_NS_SEPARATOR on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/bugs/076-024-tokenizer-keyword-substitution.php (Syntax error, unexpected T_GOTO, expecting T_STRING on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/bugs/076-029-tokenizer-keyword-substitution.php (Syntax error, unexpected T_NAMESPACE, expecting T_STRING on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/bugs/076-031-tokenizer-keyword-substitution.php (Syntax error, unexpected T_NS_C, expecting T_STRING on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/bugs/149/testHelperThrowsExceptionWithExpectedExceptionMessage.php (Syntax error, unexpected EOF, expecting T_STRING on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/bugs/149/testHelperThrowsExceptionForInvalidToken.php (Syntax error, unexpected EOF, expecting T_STRING on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/bugs/098/testDefaultPackageDoesNotContainClassWithBrokenMethod.php (Syntax error, unexpected '(', expecting ')' on line 4)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/bugs/098/testDefaultPackageDoesNotContainFunctionWithBrokenSignature.php (Syntax error, unexpected '*', expecting ')' on line 4)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/bugs/098/testDefaultPackageDoesNotContainsInterfaceWithBrokenBody.php (Syntax error, unexpected ';', expecting T_FUNCTION on line 3)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/issues/002-018-resolve-qualified-type-names.php (Trying to get property of non-object)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/issues/002-007-namespace-declaration.php (Trying to get property of non-object)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/issues/002-004-use-declaration.php (Syntax error, unexpected T_AS, expecting T_STRING on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/issues/002-022-resolve-qualified-type-names.php (Trying to get property of non-object)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/issues/002-008-namespace-declaration.php (Syntax error, unexpected ';', expecting T_STRING or T_NS_SEPARATOR or '{' on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/issues/002-009-namespace-declaration.php (Syntax error, unexpected '{', expecting T_STRING on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/issues/061/testCommandPrintsExceptionMessageWhenAnErrorOccuredDuringTheParsingProcess/UnexpectedTokenInParameterDefaultValue.php (Syntax error, unexpected T_FUNCTION, expecting ')' on line 7)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/issues/061/testCommandPrintsExpectedOutputWhenAnErrorOccuredDuringTheParsingProcess/UnexpectedTokenInParameterDefaultValue.php (Syntax error, unexpected T_FUNCTION, expecting ')' on line 7)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/issues/061/testPHPDependReturnsExpectedExceptionInstances/UnexpectedTokenInParameterDefaultValue.php (Syntax error, unexpected T_FUNCTION, expecting ')' on line 7)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/issues/061/testRunnerReturnsTrueWhenAnErrorOccuredDuringTheParsingProcess/UnexpectedTokenInParameterDefaultValue.php (Syntax error, unexpected T_FUNCTION, expecting ')' on line 7)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/issues/067/testParserThrowsExpectedExceptionForMissingDefaultValue.php (Syntax error, unexpected ')' on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/issues/067/testParserThrowsExpectedExceptionWhenReachesEofWhileParsingDefaultValue.php (Syntax error, unexpected EOF on line 4)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/issues/067/testParserThrowsExpectedExceptionWhenDefaultValueContainsInvalidToken.php (Syntax error, unexpected '*', expecting ')' on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/TextUI/Runner/testRunnerHasParseErrorsReturnsTrueForInvalidSource.php (Syntax error, unexpected '}', expecting ';' or '{' on line 10)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/TextUI/Runner/testRunnerGetParseErrorsReturnsArrayWithParsingExceptionMessages.php (Syntax error, unexpected '}', expecting ';' or '{' on line 10)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/testParserThrowsUnexpectedTokenExceptionForInvalidTokenInParameterDefaultValue.php (Syntax error, unexpected '&', expecting ')' on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/testParserThrowsUnexpectedTokenExceptionForInvalidTokenInPropertyDeclaration.php (Syntax error, unexpected T_CONST, expecting T_FUNCTION on line 4)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/ASTArgumentsParsing/testUnclosedArgumentsExpressionThrowsExpectedException.php (Syntax error, unexpected T_VARIABLE on line 4)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/testParserWithUnclosedClassFail.php (Syntax error, unexpected EOF, expecting T_FUNCTION on line 10)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/testParserWithInvalidFunction2Fail.php (Syntax error, unexpected T_STRING, expecting '(' on line 3)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/testParseExpressionUntilThrowsExceptionForUnclosedStatement.php (Syntax error, unexpected '}' on line 5)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/testParserThrowsUnexpectedTokenExceptionForInvalidTokenInMethodDeclaration.php (Syntax error, unexpected '&', expecting T_FUNCTION on line 4)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/testParserThrowsUnexpectedTokenExceptionForInvalidTokenInClassBody.php (Syntax error, unexpected ';', expecting T_FUNCTION on line 4)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/testParserThrowsUnexpectedTokenExceptionForBrokenParameterArrayDefaultValue.php (Syntax error, unexpected '{', expecting ')' on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/NamespaceResoving/testNamespacesAreLookedUpCorrectlyInThirdOfMultipleNamespaces.php (Trying to get property of non-object)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/NamespaceResoving/testNamespacesAreLookedUpCorrectlyInSecondOfMultipleNamespaces.php (Trying to get property of non-object)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/NamespaceResoving/testNamespacesAreLookedUpCorrectlyInFirstOfMultipleNamespaces.php (Trying to get property of non-object)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/testParserWithUnclosedFunctionFail.php (Syntax error, unexpected EOF on line 4)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/testParserWithInvalidFunction1Fail.php (Syntax error, unexpected '(', expecting T_VARIABLE on line 3)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/VersionAllParser/testParserAcceptsInsteadofAsInterfaceName.php (Syntax error, unexpected T_INSTEADOF, expecting T_STRING on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/VersionAllParser/testParserAcceptsTraitAsMethodName.php (Syntax error, unexpected T_TRAIT, expecting T_STRING on line 4)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/VersionAllParser/testParserAcceptsTraitConstantAsMethodName.php (Syntax error, unexpected T_TRAIT_C, expecting T_STRING on line 4)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/VersionAllParser/testParserAcceptsUseAsInterfaceName.php (Syntax error, unexpected T_USE, expecting T_STRING on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/VersionAllParser/testParserAcceptsGotoAsFunctionName.php (Syntax error, unexpected T_GOTO, expecting T_STRING or '(' on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/VersionAllParser/testParserAcceptsGotoKeywordAsMethodName.php (Syntax error, unexpected T_GOTO, expecting T_STRING on line 4)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/VersionAllParser/testParserAcceptsNamespaceAsClassName.php (Syntax error, unexpected T_NAMESPACE, expecting T_STRING on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/VersionAllParser/testParserAcceptsNamespaceKeywordAsMethodName.php (Syntax error, unexpected T_NAMESPACE, expecting T_STRING on line 4)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/VersionAllParser/testParserAcceptsTraitAsFunctionName.php (Syntax error, unexpected T_TRAIT, expecting T_STRING or '(' on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/VersionAllParser/testParserThrowsExpectedExceptionOnTokenStreamEnd.php (Syntax error, unexpected EOF, expecting T_STRING on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/VersionAllParser/testParserAcceptsDirConstantAsFunctionName.php (Syntax error, unexpected T_DIR, expecting T_STRING or '(' on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/VersionAllParser/testParserAcceptsNamespaceConstantAsInterfaceName.php (Syntax error, unexpected T_NS_C, expecting T_STRING on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/VersionAllParser/testParserAcceptsGotoKeywordAsInterfaceName.php (Syntax error, unexpected T_GOTO, expecting T_STRING on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/VersionAllParser/testParserAcceptsTraitConstantAsInterfaceName.php (Syntax error, unexpected T_TRAIT_C, expecting T_STRING on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/VersionAllParser/testParserAcceptsUseAsClassName.php (Syntax error, unexpected T_USE, expecting T_STRING on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/VersionAllParser/testParserAcceptsUseKeywordAsMethodName.php (Syntax error, unexpected T_USE, expecting T_STRING on line 4)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/VersionAllParser/testParserAcceptsNamespaceConstantAsFunctionName.php (Syntax error, unexpected T_NS_C, expecting T_STRING or '(' on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/VersionAllParser/testParserAcceptsDirConstantAsMethodName.php (Syntax error, unexpected T_DIR, expecting T_STRING on line 4)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/VersionAllParser/testParserAcceptsTraitConstantAsFunctionName.php (Syntax error, unexpected T_TRAIT_C, expecting T_STRING or '(' on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/VersionAllParser/testParserAcceptsTraitAsClassName.php (Syntax error, unexpected T_TRAIT, expecting T_STRING on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/VersionAllParser/testParserAcceptsNamespaceKeywordAsFunctionName.php (Syntax error, unexpected T_NAMESPACE, expecting T_STRING or '(' on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/VersionAllParser/testParserThrowsExpectedExceptionForTokenStreamEnd.php (Syntax error, unexpected EOF, expecting T_STRING on line 4)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/VersionAllParser/testParserAcceptsTraitAsInterfaceName.php (Syntax error, unexpected T_TRAIT, expecting T_STRING on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/VersionAllParser/testParserAcceptsDirConstantAsClassName.php (Syntax error, unexpected T_DIR, expecting T_STRING on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/VersionAllParser/testParserThrowsExceptionForInvalidBinaryIntegerLiteral.php (Syntax error, unexpected T_LNUMBER on line 6)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/VersionAllParser/testParserAcceptsNamespaceAsInterfaceName.php (Syntax error, unexpected T_NAMESPACE, expecting T_STRING on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/VersionAllParser/testParserAcceptsTraitConstantAsClassName.php (Syntax error, unexpected T_TRAIT_C, expecting T_STRING on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/VersionAllParser/testParserAcceptsInsteadofAsClassName.php (Syntax error, unexpected T_INSTEADOF, expecting T_STRING on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/VersionAllParser/testParserAcceptsNamespaceConstantAsMethodName.php (Syntax error, unexpected T_NS_C, expecting T_STRING on line 4)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/VersionAllParser/testParserThrowsExpectedExceptionForInvalidToken.php (Syntax error, unexpected T_ARRAY, expecting T_STRING on line 4)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/VersionAllParser/testParserAcceptsNamespaceConstantAsClassName.php (Syntax error, unexpected T_NS_C, expecting T_STRING on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/VersionAllParser/testParserAcceptsDirConstantAsInterfaceName.php (Syntax error, unexpected T_DIR, expecting T_STRING on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/VersionAllParser/testParserAcceptsGotoKeywordAsClassName.php (Syntax error, unexpected T_GOTO, expecting T_STRING on line 2)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Parser/testParserThrowsExpectedExceptionWhenDefaultStaticDefaultValueNotExists.php (Syntax error, unexpected ';' on line 4)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Code/ASTTraitAdaptationPrecedence/testTraitAdaptationPrecedenceWithoutQualifiedReferenceThrowsExpectedException.php (Syntax error, unexpected T_INSTEADOF, expecting T_PAAMAYIM_NEKUDOTAYIM on line 7)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Code/ASTLiteral/testUnclosedDoubleQuoteStringResultsInExpectedException.php (Syntax error, unexpected EOF, expecting T_VARIABLE or T_DOLLAR_OPEN_CURLY_BRACES or T_CURLY_OPEN on line 5)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Code/ASTLiteral/testLiteralWithBrokenBinaryIntegerThrowsExpectedException.php (Syntax error, unexpected T_LNUMBER on line 4)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Code/ASTTryStatement/testParserThrowsExceptionWhenNoCatchStatementFollows.php (Cannot use try without catch or finally on line 7)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Code/ASTString/testUnclosedDoubleQuoteStringResultsInExpectedException.php (Syntax error, unexpected T_ENCAPSED_AND_WHITESPACE on line 3)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Code/ASTIfStatement/testParserThrowsExpectedExceptionWhenIfStatementHasNoBody.php (Syntax error, unexpected '}' on line 6)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Code/ASTSwitchLabel/testParserThrowsExceptionForUnclosedSwitchLabelBody.php (Syntax error, unexpected EOF, expecting T_CASE or T_DEFAULT or '}' on line 7)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Code/ASTSwitchStatement/testInvalidStatementInSwitchStatementResultsInExpectedException.php (Syntax error, unexpected T_BREAK, expecting T_CASE or T_DEFAULT or '}' on line 5)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Code/ASTSwitchStatement/testUnclosedSwitchStatementResultsInExpectedException.php (Syntax error, unexpected EOF on line 7)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Code/ASTCompoundVariable/testUnclosedCompoundVariableThrowsExpectedException.php (Syntax error, unexpected '{' on line 4)
[01.04.2014 - 15:32:07]  - ./vendor/pdepend/pdepend/src/test/resources/files/Code/ASTForeachStatement/testForeachStatementThrowsExpectedExceptionForKeyByReference.php (Syntax error, unexpected T_DOUBLE_ARROW, expecting T_OBJECT_OPERATOR on line 4)
[01.04.2014 - 15:32:07] Saving results to directory './docs/api/xml'


Oups... phpDox encountered a problem and has terminated!

It most likely means you've found a bug, so please file a report for this
and paste the following details and the stacktrace (if given) along:

PHP Version: 5.5.9 (Linux)
PHPDox Version: 0.6.5
Exception: TheSeer\fDOM\fDOMException (Code: 1)
Location: phar:///opt/lampp/bin/phpdox/fDOMDocument-1.3.2/TheSeer/fDOMDocument/fDOMDocument.php (Line 137)

loading file './docs/api/xml/interfaces/D.xml' failed.

[XML-STRING] [Line: 0 - Column: 0] Warning 1549: failed to load external entity "/opt/lampp/htdocs/domains/wellnessbon.nl/docs/api/xml/interfaces/D.xml"


#0 phar:///opt/lampp/bin/phpdox/phpdox/collector/project/Project.php(253): TheSeer\phpDox\Collector\Project->findAffectedUnits()
#1 phar:///opt/lampp/bin/phpdox/phpdox/Application.php(138): TheSeer\phpDox\Collector\Project->save()
#2 phar:///opt/lampp/bin/phpdox/phpdox/CLI.php(148): TheSeer\phpDox\Application->runCollector()
#3 /opt/lampp/bin/phpdox(510): TheSeer\phpDox\CLI->run()

```

**Comment by theseer** [comment]
No Feedback or updates provided.
If the problem re-appears, please open a new ticket.
