### ISSUE TITLE
Error resolving HTML components on OS X

### ISSUE THREAD

**Issue by azcoppen** [theseer/phpdox#176]
```bash
wget http://phpdox.de/releases/phpdox.phar
chmod +x phpdox.phar
mv phpdox.phar /usr/local/bin/phpdox
phpdox --version
```
phpDox 0.7.0 - Copyright (C) 2010 - 2014 by Arne Blankerts

Created phpdox.xml in project directory:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<phpdox xmlns="http://phpdox.net/config">
    <project name="project Name" source="${basedir}/src" workdir="${basedir}/phpdox/build/api/xml">
        <collector backend="parser" />
        <generator output="${basedir}/public/docs">
            <build engine="html" output="html"/>
        </generator>
    </project>
</phpdox>
```
Result of running phpdox:
```bash
PHP Version: 5.5.18 (Darwin)
PHPDox Version: 0.7.0
Exception: TheSeer\fXSL\fXSLTProcessorException (Code: 2)
Location: phar:///usr/local/bin/phpdox/fXSL-1.0.4/TheSeer/fXSL/fxsltprocessor.php (Line 251)

Error while importing given stylesheet

[XML-STRING] [Line: 0 - Column: 0] Warning 1549: failed to load external entity "phar:/usr/local/bin/phpdox/templates/html/components.xsl"
[XML-STRING] [Line: 0 - Column: 0] Error 1: compilation error: file phar:///usr/local/bin/phpdox/phpdox/generator/engine/html/../../../../templates/html/class.xsl line 8 element import
[XML-STRING] [Line: 0 - Column: 0] Error 1: xsl:import : unable to load phar:/usr/local/bin/phpdox/templates/html/components.xsl
[XML-STRING] [Line: 0 - Column: 0] Warning 1549: failed to load external entity "phar:/usr/local/bin/phpdox/templates/html/functions.xsl"
[XML-STRING] [Line: 0 - Column: 0] Error 1: compilation error: file phar:///usr/local/bin/phpdox/phpdox/generator/engine/html/../../../../templates/html/class.xsl line 9 element import
[XML-STRING] [Line: 0 - Column: 0] Error 1: xsl:import : unable to load phar:/usr/local/bin/phpdox/templates/html/functions.xsl
[XML-STRING] [Line: 0 - Column: 0] Warning 1549: failed to load external entity "phar:/usr/local/bin/phpdox/templates/html/synopsis.xsl"
[XML-STRING] [Line: 0 - Column: 0] Error 1: compilation error: file phar:///usr/local/bin/phpdox/phpdox/generator/engine/html/../../../../templates/html/class.xsl line 10 element import
[XML-STRING] [Line: 0 - Column: 0] Error 1: xsl:import : unable to load phar:/usr/local/bin/phpdox/templates/html/synopsis.xsl


#0 phar:///usr/local/bin/phpdox/phpdox/generator/engine/html/Html.php(208): TheSeer\fXSL\fXSLTProcessor->transformToDoc()
#1 unknown(0): TheSeer\phpDox\Generator\Engine\Html->buildClass()
#2 phar:///usr/local/bin/phpdox/phpdox/generator/Generator.php(203): call_user_func()
#3 phar:///usr/local/bin/phpdox/phpdox/generator/Generator.php(277): TheSeer\phpDox\Generator\Generator->handleEvent()
#4 phar:///usr/local/bin/phpdox/phpdox/generator/Generator.php(249): TheSeer\phpDox\Generator\Generator->processClass()
#5 phar:///usr/local/bin/phpdox/phpdox/generator/Generator.php(142): TheSeer\phpDox\Generator\Generator->processWithNamespace()
#6 phar:///usr/local/bin/phpdox/phpdox/Application.php(238): TheSeer\phpDox\Generator\Generator->run()
#7 phar:///usr/local/bin/phpdox/phpdox/CLI.php(152): TheSeer\phpDox\Application->runGenerator()
#8 /usr/local/bin/phpdox(460): TheSeer\phpDox\CLI->run()
```

Remove the line
```xml
<build engine="html" output="html"/>
```
and it generates the XML successfully.

**Comment by theseer** [comment]
Can you verify if this still happens with the latest master?

**Comment by theseer** [comment]
ping?

**Comment by theseer** [comment]
No feedback provided. If the problem still exists with 0.8 release, please open a new issue.

**Comment by designermonkey** [comment]
I have just hit this issue also. Installed phpdox via homebrew if that's any help?

```
phpDox 0.8.1.1 - Copyright (C) 2010 - 2016 by Arne Blankerts
```

**Comment by theseer** [comment]
Since I have no idea how homebrew packages phpDox that's at least an interesting information but does not yet help very much. Can you give me some more input, e.g. paste the relevant sections of the phpdox.xml config file as well as some more of the oput?

**Comment by designermonkey** [comment]
Sorry, I completely forgot to post my next comment yesterday (was rushing about):

This is actually the same issue as the phar issue #255, where the phar is not able to access the xsl properly.

You can close this again, sorry :)

**Comment by theseer** [comment]
Done,
