### ISSUE TITLE
Windows 8.1 x64 Error Importing Stylesheets

### ISSUE THREAD

**Issue by jtwebb** [theseer/phpdox#221]
I know this has been an error in the past and the issues have been closed, but I still don't think the issue is fixed. Here is the stacktrace I received:

```
PHP Version: 5.6.7 (WINNT)
PHPDox Version: 0.7.0
Exception: TheSeer\fXSL\fXSLTProcessorException (Code: 2)
Location: phar://E:/bin/phpdox/phpdox.phar/fXSL-1.0.4/TheSeer/fXSL/fxsltprocessor.php (Line 251)

Error while importing given stylesheet

[XML-STRING] [Line: 0 - Column: 0] Warning 1549: failed to load external entity "phar%3A/E%3A/bin/phpdox/phpdox.phar/templates/html/components.xsl"
[XML-STRING] [Line: 0 - Column: 0] Error 1: compilation error: file phar%3A//E%3A/bin/phpdox/phpdox.phar/phpdox/generator/engine/html/../../../../templates/html/class.xsl line 8 element import
[XML-STRING] [Line: 0 - Column: 0] Error 1: xsl:import : unable to load phar%3A/E%3A/bin/phpdox/phpdox.phar/templates/html/components.xsl
[XML-STRING] [Line: 0 - Column: 0] Warning 1549: failed to load external entity "phar%3A/E%3A/bin/phpdox/phpdox.phar/templates/html/functions.xsl"
[XML-STRING] [Line: 0 - Column: 0] Error 1: compilation error: file phar%3A//E%3A/bin/phpdox/phpdox.phar/phpdox/generator/engine/html/../../../../templates/html/class.xsl line 9 element import
[XML-STRING] [Line: 0 - Column: 0] Error 1: xsl:import : unable to load phar%3A/E%3A/bin/phpdox/phpdox.phar/templates/html/functions.xsl
[XML-STRING] [Line: 0 - Column: 0] Warning 1549: failed to load external entity "phar%3A/E%3A/bin/phpdox/phpdox.phar/templates/html/synopsis.xsl"
[XML-STRING] [Line: 0 - Column: 0] Error 1: compilation error: file phar%3A//E%3A/bin/phpdox/phpdox.phar/phpdox/generator/engine/html/../../../../templates/html/class.xsl line 10 element import
[XML-STRING] [Line: 0 - Column: 0] Error 1: xsl:import : unable to load phar%3A/E%3A/bin/phpdox/phpdox.phar/templates/html/synopsis.xsl


#0 phar://E:/bin/phpdox/phpdox.phar/phpdox/generator/engine/html/Html.php(208): TheSeer\fXSL\fXSLTProcessor->transformToDoc()
#1 unknown(0): TheSeer\phpDox\Generator\Engine\Html->buildClass()
#2 phar://E:/bin/phpdox/phpdox.phar/phpdox/generator/Generator.php(203): call_user_func()
#3 phar://E:/bin/phpdox/phpdox.phar/phpdox/generator/Generator.php(277): TheSeer\phpDox\Generator\Generator->handleEvent()
#4 phar://E:/bin/phpdox/phpdox.phar/phpdox/generator/Generator.php(249): TheSeer\phpDox\Generator\Generator->processClass()
#5 phar://E:/bin/phpdox/phpdox.phar/phpdox/generator/Generator.php(142): TheSeer\phpDox\Generator\Generator->processWithNamespace()
#6 phar://E:/bin/phpdox/phpdox.phar/phpdox/Application.php(238): TheSeer\phpDox\Generator\Generator->run()
#7 phar://E:/bin/phpdox/phpdox.phar/phpdox/CLI.php(152): TheSeer\phpDox\Application->runGenerator()
#8 E:\bin\phpdox\phpdox.phar(460): TheSeer\phpDox\CLI->run()
```

In case it's an error with my config file (this is my first time using phpdox), here is my config file

```xml
<phpdox xmlns="http://phpdox.net/config">
    <project name="my_project" source="src" workdir="./build/phpdox">
        <collector publiconly="false">
            <include mask="*.php" />
        </collector>

        <generator output="build">
            <build engine="html" enabled="true" output="api">
                <file extension="html" />
            </build>
        </generator>
    </project>
</phpdox>
```
Any ideas on what could be causing this? I've forked the repo and tried having a look around but I'm not 100% sure what I'm looking for. If someone thinks they have an answer, I'm more than happy to test it out on my machine.

**Comment by jtwebb** [comment]
Never mind. After playing with the config file a little bit I determined it was a configuration error. My new xml file looks like this:

```xml
<phpdox xmlns="http://phpdox.net/config">
    <project name="my_project" source="/full/path/to/src" workdir="/full/path/to/build/phpdox">
        <collector publiconly="false">
            <include mask="*.php" />
        </collector>

        <generator output="/full/path/to/docs">
            <build engine="html" enabled="true" output="api">
                <!-- ***** The following line is what made all the difference! ***** -->
                <template dir="${phpDox.home}/templates/html" />
                <file extension="html" />
            </build>
        </generator>
    </project>
</phpdox>
```
