### ISSUE TITLE
File '' not found!

### ISSUE THREAD

**Issue by Johoni** [theseer/phpdox#252]
Hi,
I'm not sure if it is a bug like in #164  because i have no whitespaces. 
If i access the path for the file 'autoload.php.xml' in my windows explorer i find it.
   [phpdox] 
   [phpdox] PHP Version: 5.6.14 (WINNT)
   [phpdox] PHPDox Version: 0.8.1
   [phpdox] Exception: TheSeer\phpDox\Generator\TokenFileException (Code: 1)
   [phpdox] Location: phar://C:/Apache24/php/phpdox.phar/phpdox/generator/project/TokenFile.php (Line 19)
   [phpdox] 
   [phpdox] File 'file:/D:/XXX/workspace/build/phpdox/tokens/Autoload.php.xml' not found
   [phpdox]

**Comment by stmeyer** [comment]
Same for me:
```
   [phpdox] Oups... phpDox encountered a problem and has terminated!
   [phpdox] 
   [phpdox] It most likely means you've found a bug, so please file a report for this
   [phpdox] and paste the following details and the stacktrace (if given) along:
   [phpdox] 
   [phpdox] PHP Version: 5.6.15 (WINNT)
   [phpdox] PHPDox Version: 0.8.2-dev
   [phpdox] Exception: TheSeer\phpDox\Generator\TokenFileException (Code: 1)
   [phpdox] Location: C:\inetpub\wwwroot\composer\vendor\theseer\phpdox\src\generator\project\TokenFile.php (Line 19)
   [phpdox] 
   [phpdox] File 'file:/C:/Program Files (x86)/Jenkins/jobs/MES Web/workspace/build/phpdox/xml/tokens/Auth/Authenticate.php.xml' not found
   [phpdox] 
   [phpdox] #0 C:\inetpub\wwwroot\composer\vendor\theseer\phpdox\src\generator\Generator.php(153): TheSeer\phpDox\Generator\TokenFileIterator->current()
   [phpdox] #1 C:\inetpub\wwwroot\composer\vendor\theseer\phpdox\src\generator\Generator.php(146): TheSeer\phpDox\Generator\Generator->processTokenFiles()
   [phpdox] #2 C:\inetpub\wwwroot\composer\vendor\theseer\phpdox\src\Application.php(241): TheSeer\phpDox\Generator\Generator->run()
   [phpdox] #3 C:\inetpub\wwwroot\composer\vendor\theseer\phpdox\src\CLI.php(165): TheSeer\phpDox\Application->runGenerator()
   [phpdox] #4 C:\inetpub\wwwroot\composer\vendor\theseer\phpdox\phpdox(68): TheSeer\phpDox\CLI->run()
   [phpdox] 
   [phpdox] 
   [phpdox] 
   [phpdox] .................................................
   [phpdox] Result: 5
```
In Explorer the file exists. Installed with composer:
```composer global require theseer/phpdox```

**Comment by stmeyer** [comment]
Any news? Do you need more information?

**Comment by theseer** [comment]
Going to track this issue in #271
