### ISSUE TITLE
error while simple execute phpdox - -engines

### ISSUE THREAD

**Issue by HuVaale** [theseer/phpdox#267]
Here the details and the stacktrace:

```
PHP Version: 7.0.4-5+deb.sury.org~wily+1 (Linux)
PHPDox Version: 0.8.1.1
ErrorException: E_NOTICE 
Location: phar:///usr/bin/phpdox/phpdox/CLIOptions.php (Line 162)
```

Uninitialized string offset: 1

```
#0 phar:///usr/bin/phpdox/phpdox/CLIOptions.php(75): TheSeer\phpDox\CLIOptions->parse()
#1 phar:///usr/bin/phpdox/phpdox/CLI.php(95): TheSeer\phpDox\CLIOptions->showHelp()
#2 /usr/bin/phpdox(450): TheSeer\phpDox\CLI->run()
```

**Comment by theseer** [comment]
Thanks for reporting this.
I fail to reproduce the error - neither in 5.6 nor 7.0.4 - i get the NOTICE you pasted:

```
theseer@nyda /tmp/x $ phive install phpdox
Phive 0.2.0-23-ga3b5b70 - Copyright (C) 2015-2016 by Arne Blankerts, Sebastian Heuer and Contributors

Downloading https://phar.io/data/phpdox.phive.xml
Downloading https://github.com/theseer/phpdox/releases/download/0.8.1.1/phpdox-0.8.1.1.phar
Downloading https://github.com/theseer/phpdox/releases/download/0.8.1.1/phpdox-0.8.1.1.phar.asc
Downloading key 2A8299CE842DD38C
Trying https://hkps.pool.sks-keyservers.net
Sucessfully downloaded key

	Fingerprint: BEEB 9AED 51C2 8445 FAB1 4222 8DDB 46C4 EA2E BCDC

	Arne Blankerts <Arne@Blankerts.de> (2015-09-23)
	Arne Blankerts (Keybase.io) <theseer@keybase.io> (2015-09-23)

	Created: 2009-03-14

Import this key? [Y|n] y
Symlinking phpdox-0.8.1.1.phar to /tmp/x/tools/phpdox
```

```
theseer@nyda /tmp/x $ php70 -v
PHP 7.0.4 (cli) (built: Mar  2 2016 16:41:32) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
```

```
theseer@nyda /tmp/x $ php70 /tmp/x/tools/phpdox --skel > phpdox.xml
theseer@nyda /tmp/x $ php70 /tmp/x/tools/phpdox --engines
phpDox 0.8.1.1 - Copyright (C) 2010 - 2016 by Arne Blankerts

[13.03.2016 - 14:59:11] Using config file './phpdox.xml'
[13.03.2016 - 14:59:11] Registered collector backend 'parser'
[13.03.2016 - 14:59:11] Registered enricher 'build'
[13.03.2016 - 14:59:11] Registered enricher 'git'
[13.03.2016 - 14:59:11] Registered enricher 'checkstyle'
[13.03.2016 - 14:59:11] Registered enricher 'phpcs'
[13.03.2016 - 14:59:11] Registered enricher 'pmd'
[13.03.2016 - 14:59:11] Registered enricher 'phpunit'
[13.03.2016 - 14:59:11] Registered enricher 'phploc'
[13.03.2016 - 14:59:11] Registered output engine 'xml'
[13.03.2016 - 14:59:11] Registered output engine 'html'

The following engines are registered:

   xml 	 Raw XML Output saver after enrichment
   html 	 Simple HTML Output builder
```

What am I missing?

**Comment by theseer** [comment]
Ah, that happens when you type ```-{space}-engines```.
