### ISSUE TITLE
Generate Error

### ISSUE THREAD

**Issue by weelion** [theseer/phpdox#288]
```
PHP Version: 7.0.10 (Darwin)
PHPDox Version: 0.9.0
Exception: TypeError (Code: 0)
Location: phar:///Users/weelion/MyProject/build/tools/phpdox.phar/phpdox/generator/engine/AbstractEngine.php (Line 59)

Argument 1 passed to TheSeer\phpDox\Generator\Engine\AbstractEngine::saveDomDocument() must be an instance of DOMDocument, boolean given, called in phar:///Users/weelion/MyProject/build/tools/phpdox.phar/phpdox/generator/engine/html/Html.php on line 210

#0 unknown(0): TheSeer\phpDox\Generator\Engine\Html->buildClass()
#1 phar:///Users/weelion/MyProject/build/tools/phpdox.phar/phpdox/generator/Generator.php(203): call_user_func()
#2 phar:///Users/weelion/MyProject/build/tools/phpdox.phar/phpdox/generator/Generator.php(277): TheSeer\phpDox\Generator\Generator->handleEvent()
#3 phar:///Users/weelion/MyProject/build/tools/phpdox.phar/phpdox/generator/Generator.php(249): TheSeer\phpDox\Generator\Generator->processClass()
#4 phar:///Users/weelion/MyProject/build/tools/phpdox.phar/phpdox/generator/Generator.php(142): TheSeer\phpDox\Generator\Generator->processWithNamespace()
#5 phar:///Users/weelion/MyProject/build/tools/phpdox.phar/phpdox/Application.php(239): TheSeer\phpDox\Generator\Generator->run()
#6 phar:///Users/weelion/MyProject/build/tools/phpdox.phar/phpdox/CLI.php(165): TheSeer\phpDox\Application->runGenerator()
#7 /Users/weelion/MyProject/build/tools/phpdox.phar(461): TheSeer\phpDox\CLI->run()
```

**Comment by theseer** [comment]
Thank you for reporting this.

This is a very interesting crash, as it means the XSL Transformation failed without *any* indication of an error. I'm a bit lost as to how to reproduce this...
