### ISSUE TITLE
Class 'PhpParser\ErrorHandler\Throwing' not found

### ISSUE THREAD

**Issue by heisian** [theseer/phpdox#292]
```
PHP Version: 7.1.0RC5 (Darwin)
PHPDox Version: 0.8.2-dev
Exception: Error (Code: 0)
Location: /Users/revolver/.composer/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php (Line 28)

Class 'PhpParser\ErrorHandler\Throwing' not found

#0 /Users/revolver/.composer/vendor/theseer/phpdox/src/collector/Collector.php(141): TheSeer\phpDox\Collector\Backend\PHPParser->parse()
#1 /Users/revolver/.composer/vendor/theseer/phpdox/src/collector/Collector.php(105): TheSeer\phpDox\Collector\Collector->processFile()
#2 /Users/revolver/.composer/vendor/theseer/phpdox/src/Application.php(122): TheSeer\phpDox\Collector\Collector->run()
#3 /Users/revolver/.composer/vendor/theseer/phpdox/src/CLI.php(161): TheSeer\phpDox\Application->runCollector()
#4 /Users/revolver/.composer/vendor/theseer/phpdox/phpdox(67): TheSeer\phpDox\CLI->run()
```

I downgraded to ^0.8.0 and phpdox works fine, so seems just latest version has issues

**Comment by theseer** [comment]
That looks like a duplicate for #289
