### ISSUE TITLE
phpDox 0.11.0-dev Oups on Windows10 x64 PHP 7.1.7RC1

### ISSUE THREAD

**Issue by interactiveci** [theseer/phpdox#311]
```
[11.08.2017 - 07:20:31] Saving results to directory 'build/phpdox'
[11.08.2017 - 07:20:31] Collector process completed

[11.08.2017 - 07:20:31] Starting generator
[11.08.2017 - 07:20:31] Loading enrichers
[11.08.2017 - 07:20:31] Enricher PHPLoc xml initialized successfully
[11.08.2017 - 07:20:31] Enricher Build Information initialized successfully
[11.08.2017 - 07:20:31] Starting event loop.

..................................................      [50]
..................................................      [100]
..................................................      [150]
............................................

Oups... phpDox encountered a problem and has terminated!

It most likely means you've found a bug, so please file a report for this
and paste the following details and the stacktrace (if given) along:

PHP Version: 7.1.7RC1 (WINNT)
PHPDox Version: 0.11.0-dev
Exception: TheSeer\phpDox\Generator\TokenFileException (Code: 1)
Location: D:\JENKINS\workspace\RichardLaptopWindows10\vendor\theseer\phpdox\src\generator\project\TokenFile.php (Line 19)

File 'file:/D:/JENKINS/workspace/RichardLaptopWindows10/build/phpdox/tokens/app/Console/Kernel.php.xml' not found

#0 D:\JENKINS\workspace\RichardLaptopWindows10\vendor\theseer\phpdox\src\generator\Generator.php(153): TheSeer\phpDox\Generator\TokenFileIterator->current()
#1 D:\JENKINS\workspace\RichardLaptopWindows10\vendor\theseer\phpdox\src\generator\Generator.php(146): TheSeer\phpDox\Generator\Generator->processTokenFiles()
#2 D:\JENKINS\workspace\RichardLaptopWindows10\vendor\theseer\phpdox\src\Application.php(239): TheSeer\phpDox\Generator\Generator->run()
#3 D:\JENKINS\workspace\RichardLaptopWindows10\vendor\theseer\phpdox\src\CLI.php(165): TheSeer\phpDox\Application->runGenerator()
#4 D:\JENKINS\workspace\RichardLaptopWindows10\vendor\theseer\phpdox\phpdox(79): TheSeer\phpDox\CLI->run()
```

**Comment by interactiveci** [comment]
The File Kernel.php.xml exists
```
<username>@<hostname> /cygdrive/d/JENKINS/workspace/RichardLaptopWindows10
$ ls -al build/phpdox/tokens/app/Console/Kernel.php.xml
-rwxrwx---+ 1 <username> Domänen-Benutzer 6729 11. Aug 09:15 build/phpdox/tokens/app/Console/Kernel.php.xml

<username>@<hostname> /cygdrive/d/JENKINS/workspace/RichardLaptopWindows10
```

**Comment by theseer** [comment]
This looks like to be the same issue as #252.

**Comment by theseer** [comment]
Maybe it's not though as your path does not included a space. The error location is the same though.
It's really hard to investigate, since I don't use windows and drive letters really are an anachronism.

**Comment by theseer** [comment]
Considering this a duplicate to #271
