### ISSUE TITLE
Class 'PhpParser\ErrorHandler\Throwing' not found

### ISSUE THREAD

**Issue by rauwebieten** [theseer/phpdox#337]
I installed the dev-master, but I still have the 0.8.2 release installed

PHP Version: 7.1.4 (WINNT)
PHPDox Version: 0.8.2-dev
Exception: Error (Code: 0)
Location: C:\Users\Peter\PhpstormProjects\PHPJenkinsPOC\vendor\nikic\php-parser\lib\PhpParser\Parser\Multiple.php (Line 28)

Class 'PhpParser\ErrorHandler\Throwing' not found

#0 C:\Users\Peter\PhpstormProjects\PHPJenkinsPOC\vendor\theseer\phpdox\src\collector\Collector.php(141): TheSeer\phpDox\Collector\Backend\PHPParser->parse()
#1 C:\Users\Peter\PhpstormProjects\PHPJenkinsPOC\vendor\theseer\phpdox\src\collector\Collector.php(105): TheSeer\phpDox\Collector\Collector->processFile()
#2 C:\Users\Peter\PhpstormProjects\PHPJenkinsPOC\vendor\theseer\phpdox\src\Application.php(122): TheSeer\phpDox\Collector\Collector->run()
#3 C:\Users\Peter\PhpstormProjects\PHPJenkinsPOC\vendor\theseer\phpdox\src\CLI.php(161): TheSeer\phpDox\Application->runCollector()
#4 C:\Users\Peter\PhpstormProjects\PHPJenkinsPOC\vendor\theseer\phpdox\phpdox(67): TheSeer\phpDox\CLI->run()

**Comment by rauwebieten** [comment]
I made it work with the dev-master version.
