### ISSUE TITLE
Object of class PhpParser\Node\NullableType could not be converted to string

### ISSUE THREAD

**Issue by enursed** [theseer/phpdox#411]
```
Oups... phpDox encountered a problem and has terminated!

It most likely means you've found a bug, so please file a report for this
and paste the following details and the stacktrace (if given) along:

PHP Version: 7.4.11 (Linux)
PHPDox Version: 0.12.0-24-g727ac55
Exception: Error (Code: 0)
Location: /home/vagrant/.composer/vendor/theseer/phpdox/src/collector/project/AbstractVariableObject.php (Line 68)

Object of class PhpParser\Node\NullableType could not be converted to string

#0 /home/vagrant/.composer/vendor/theseer/phpdox/src/collector/project/MethodObject.php(130): TheSeer\phpDox\Collector\AbstractVariableObject->setType()
#1 /home/vagrant/.composer/vendor/theseer/phpdox/src/collector/backend/parser/UnitCollectingVisitor.php(273): TheSeer\phpDox\Collector\MethodObject->setReturnType()
#2 /home/vagrant/.composer/vendor/theseer/phpdox/src/collector/backend/parser/UnitCollectingVisitor.php(239): TheSeer\phpDox\Collector\Backend\UnitCollectingVisitor->processMethodReturnType()
#3 /home/vagrant/.composer/vendor/theseer/phpdox/src/collector/backend/parser/UnitCollectingVisitor.php(108): TheSeer\phpDox\Collector\Backend\UnitCollectingVisitor->processMethod()
#4 /home/vagrant/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): TheSeer\phpDox\Collector\Backend\UnitCollectingVisitor->enterNode()
#5 /home/vagrant/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray()
#6 /home/vagrant/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode()
#7 /home/vagrant/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray()
#8 /home/vagrant/.composer/vendor/theseer/phpdox/src/collector/backend/parser/PHPParser.php(44): PhpParser\NodeTraverser->traverse()
#9 /home/vagrant/.composer/vendor/theseer/phpdox/src/collector/Collector.php(101): TheSeer\phpDox\Collector\Backend\PHPParser->parse()
#10 /home/vagrant/.composer/vendor/theseer/phpdox/src/collector/Collector.php(71): TheSeer\phpDox\Collector\Collector->processFile()
#11 /home/vagrant/.composer/vendor/theseer/phpdox/src/Application.php(88): TheSeer\phpDox\Collector\Collector->run()
#12 /home/vagrant/.composer/vendor/theseer/phpdox/src/CLI.php(120): TheSeer\phpDox\Application->runCollector()
#13 /home/vagrant/.composer/vendor/theseer/phpdox/phpdox(68): TheSeer\phpDox\CLI->run()
```

**Comment by theseer** [comment]
Fixed in current master.
