### ISSUE TITLE
Count() bug

### ISSUE THREAD

**Issue by bellenuit** [theseer/phpdox#417]
running locally on mac os 12.0.1 return this bug

phpDox 0.8.0 - Copyright (C) 2010 - 2021 by Arne Blankerts

[28.12.2021 - 20:10:40] Using config file './phpdox.xml'
[28.12.2021 - 20:10:40] Registered collector backend 'parser'
[28.12.2021 - 20:10:40] Registered enricher 'build'
[28.12.2021 - 20:10:40] Registered enricher 'git'
[28.12.2021 - 20:10:40] Registered enricher 'checkstyle'
[28.12.2021 - 20:10:40] Registered enricher 'phpcs'
[28.12.2021 - 20:10:40] Registered enricher 'pmd'
[28.12.2021 - 20:10:40] Registered enricher 'phpunit'
[28.12.2021 - 20:10:40] Registered enricher 'phploc'
[28.12.2021 - 20:10:40] Registered output engine 'xml'
[28.12.2021 - 20:10:40] Registered output engine 'html'

Oups... phpDox encountered a problem and has terminated!

It most likely means you've found a bug, so please file a report for this
and paste the following details and the stacktrace (if given) along:

PHP Version: 7.3.29 (Darwin)
PHPDox Version: 0.8.0
ErrorException: E_WARNING 
Location: phar:///Users/matti/Dropbox/Programming/subtitler2.1/git/phpdox-0.8.0.phar/phpdox/shared/FileInfoCollection.php (Line 67)

count(): Parameter must be an array or an object that implements Countable

#0 phar:///Users/matti/Dropbox/Programming/subtitler2.1/git/phpdox-0.8.0.phar/phpdox/shared/FileInfoCollection.php(67): count()
#1 phar:///Users/matti/Dropbox/Programming/subtitler2.1/git/phpdox-0.8.0.phar/phpdox/shared/FileInfoCollection.php(53): TheSeer\phpDox\FileInfoCollection->count()
#2 phar:///Users/matti/Dropbox/Programming/subtitler2.1/git/phpdox-0.8.0.phar/phpdox/bootstrap/Bootstrap.php(56): TheSeer\phpDox\FileInfoCollection->valid()
#3 phar:///Users/matti/Dropbox/Programming/subtitler2.1/git/phpdox-0.8.0.phar/phpdox/CLI.php(129): TheSeer\phpDox\Bootstrap->load()
#4 /Users/matti/Dropbox/Programming/subtitler2.1/git/phpdox-0.8.0.phar(449): TheSeer\phpDox\CLI->run()

**Comment by quexal** [comment]
Same here:
`
phpDox 0.8.0 - Copyright (C) 2010 - 2023 by Arne Blankerts

[23.05.2023 - 23:07:00] Using config file './phpdox.xml'
[23.05.2023 - 23:07:00] Registered collector backend 'parser'
[23.05.2023 - 23:07:00] Registered enricher 'build'
[23.05.2023 - 23:07:00] Registered enricher 'git'
[23.05.2023 - 23:07:00] Registered enricher 'checkstyle'
[23.05.2023 - 23:07:00] Registered enricher 'phpcs'
[23.05.2023 - 23:07:00] Registered enricher 'pmd'
[23.05.2023 - 23:07:00] Registered enricher 'phpunit'
[23.05.2023 - 23:07:00] Registered enricher 'phploc'
[23.05.2023 - 23:07:00] Registered output engine 'xml'
[23.05.2023 - 23:07:00] Registered output engine 'html'


Oups... phpDox encountered a problem and has terminated!

It most likely means you've found a bug, so please file a report for this
and paste the following details and the stacktrace (if given) along:

PHP Version: 7.4.3-4ubuntu2.18 (Linux)
PHPDox Version: 0.8.0
ErrorException: E_WARNING
Location: phar:///usr/local/bin/phpdox/phpdox/shared/FileInfoCollection.php (Line 67)

count(): Parameter must be an array or an object that implements Countable

#0 phar:///usr/local/bin/phpdox/phpdox/shared/FileInfoCollection.php(67): count()
#1 phar:///usr/local/bin/phpdox/phpdox/shared/FileInfoCollection.php(53): TheSeer\phpDox\FileInfoCollection->count()
#2 phar:///usr/local/bin/phpdox/phpdox/bootstrap/Bootstrap.php(56): TheSeer\phpDox\FileInfoCollection->valid()
#3 phar:///usr/local/bin/phpdox/phpdox/CLI.php(129): TheSeer\phpDox\Bootstrap->load()
#4 /usr/local/bin/phpdox(449): TheSeer\phpDox\CLI->run()
`

**Comment by theseer** [comment]
Outdated version of phpDox used. This has been fixed since 2018.
