### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by dejudicibus** [theseer/phpdox#419]
I installed PhpDox on windows in folder C:\\PhpDox, created a .cmd file to launch it and added that folder to path. Then I created a phpdox.xml config file in my project and ran it. I get:

Oups... phpDox encountered a problem and has terminated!

It most likely means you've found a bug, so please file a report for this
and paste the following details and the stacktrace (if given) along:

PHP Version: 7.4.9 (WINNT)
PHPDox Version: 0.8.0
ErrorException: E_WARNING
Location: phar://C:/PhpDox/phpdox.phar/phpdox/shared/FileInfoCollection.php (Line 67)

count(): Parameter must be an array or an object that implements Countable

#0 phar://C:/PhpDox/phpdox.phar/phpdox/shared/FileInfoCollection.php(67): count()
#1 phar://C:/PhpDox/phpdox.phar/phpdox/shared/FileInfoCollection.php(53): TheSeer\phpDox\FileInfoCollection->count()
#2 phar://C:/PhpDox/phpdox.phar/phpdox/bootstrap/Bootstrap.php(56): TheSeer\phpDox\FileInfoCollection->valid()
#3 phar://C:/PhpDox/phpdox.phar/phpdox/CLI.php(129): TheSeer\phpDox\Bootstrap->load()
#4 C:\PhpDox\phpdox.phar(449): TheSeer\phpDox\CLI->run()

**Comment by theseer** [comment]
Duplicate of #315.

PHPDox 0.8.0 is seriously outdated. Upgrade to latest version.

**Comment by dejudicibus** [comment]
OK; I installed the latest version and it works, but it ignores completely all PhpDoc blocks of functions in functions.php. It just show the source code. What I need is a Reference Guide of all functions. Do I need to use some additional option?

**Comment by theseer** [comment]
Sorry, phpDox does not support functions but only classes / interfaces / traits. As in, object oriented development.
